### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by tassieg** [inpho/topic-explorer#344] opened 2018-11-19 15:20 UTC
Anaconda for Mac didn't seem to have advanced option in latest version for Install to correct PATH? I did hit "Customize" and it said "Whether to modify the bash profile file to append Anaconda3 to the PATH variable. If you do not do this, you will need to add ~/anaconda3/bin to your PATH manually to run the commands, or run all Anaconda3 commands explicitly from that path" and left it checked. But the install fails "building wheel for vsm" and then tries before sending "Command "/Users/ctgniady/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/wp/29n9n2nx3pl9dnskvs5j7g_dkr96n6/T/pip-install-7f9qwt2u/vsm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/wp/29n9n2nx3pl9dnskvs5j7g_dkr96n6/T/pip-record-mvjf7bf6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/wp/29n9n2nx3pl9dnskvs5j7g_dkr96n6/T/pip-install-7f9qwt2u/vsm/"

**Comment by adrealawrence** [comment] 2019-04-07 20:51
I have had the same issue. Is there a workaround or update?

**Comment by JaimieMurdock** [comment] 2019-04-08 00:30
I'll investigate this on Tuesday evening, will provide an update here.

**Comment by adrealawrence** [comment] 2019-04-08 01:34
Thank you!

**Comment by JaimieMurdock** [comment] 2019-04-10 14:05
@kirtansakariya has been working on this issue, we think it has to do with XCode versions. In order to have a really fast topic modeling implementation, we mixed some C code into our Python for the `vsm` modeling library. The C code requires compilation on developer machines, but on user installs, the package should have a pre-compiled binary of the C code. It seems this is not working. Kirtan's got a fix for the compilation step, and we'll be working more on packagaing - targeting Friday to have this resolved.

**Comment by adrealawrence** [comment] 2019-04-10 14:52
Many thanks!

**Comment by JaimieMurdock** [comment] 2019-04-12 05:11
So @kirtansakariya and I debugged earlier today and believe we've isolated the bug. It broke a few unit tests, but should have the packages released tomorrow.

**Comment by adrealawrence** [comment] 2019-04-16 00:49
Thank you. I'm looking forward to the update.

**Comment by JaimieMurdock** [comment] 2019-04-16 22:03
Hi @adrealawrence, we ran into a few more issues, on track to release tomorrow evening.

**Comment by JaimieMurdock** [comment] 2019-04-18 17:08
I fixed some issues last night, and found hopefully the final root cause of some runtime errors.

I had refactored the config files to use a single parser in `topicexplorer.config` however, I didn't refactor a lot of the extensions or the import/export function, so we've been having lots of errors on recent builds. 

I'm correcting those now and will push a new release by 6pm eastern.

**Comment by adrealawrence** [comment] 2019-04-18 18:00
Thanks so much, Jaimie.

**Comment by JaimieMurdock** [comment] 2019-04-18 19:16
@adrealawrence This issue has been resolved with topicexplorer 1.0b223

`pip install topicexplorer==1.0b223` should get you the upgrade!

**Closed by JaimieMurdock** 2019-04-18 19:16 UTC

**Comment by adrealawrence** [comment] 2019-04-19 02:57
@JaimieMurdock Thank you!
