### ISSUE TITLE
chinese term search needs word segmentation

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#141] opened 2016-07-20 17:02 UTC
Chinese users expect to be able to type search terms without spaces, e.g. '史记 三' but this will cause a problem since that sequence is not a single word.  Thus we need word segmentation applied to the query term.

**Comment by JaimieMurdock** [comment] 2016-10-20 00:25
Duplicate of #138

**Closed by JaimieMurdock** 2016-10-20 00:25 UTC
Labels: chinese
