### ISSUE TITLE
permissions string

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#144] opened 2016-07-26 17:41 UTC
There should be a way to associate a permissions text string with each corpus and display it in various places, including main corpus page, and whenever fulltext is displayed.

**Comment by JaimieMurdock** [comment] 2016-10-07 02:10
This permissions string should go both in the footer of the fulltext modal. Where should the notice go on each subpage? Should I create a © link in the bottom left of the sidebar with details? Some items may not be copyright though, so debating whether CC logos should be used - having a whole permissions infrastructure seems overkill though.

Welcome to any suggestions for design.

**Comment by colinallen** [comment] 2016-10-07 19:14
© link at bottom left of sidebar seems reasonable.  It could explain that source text copyright is variable per source, but CC license applies to TE visualizations and other derivatives.

On Oct 6, 2016, at 10:10 PM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:


This permissions string should go both in the footer of the fulltext modal. Where should the notice go on each subpage? Should I create a © link in the bottom left of the sidebar with details? Some items may not be copyright though, so debating whether CC logos should be used - having a whole permissions infrastructure seems overkill though.

Welcome to any suggestions for design.

**Comment by JaimieMurdock** [comment] 2016-10-09 01:46
Sample text and interface for copyright notice. Debating explicitly making derivatives [CC-BY](https://creativecommons.org/licenses/by/4.0/) to ensure attribution. Feedback requested.

![image](https://cloud.githubusercontent.com/assets/666240/19216988/8ab78e46-8da0-11e6-9916-4cb080a26f6d.png)

**Comment by colinallen** [comment] 2016-10-11 12:54
Is it correct to say "permissive MIT-style License" or should it be simply "permissive MIT license"? -- not sure where you're linking, but is it Expat = OSI/MIT https://opensource.org/licenses/MIT ?  (see also https://en.wikipedia.org/wiki/MIT_License#Variants)

**Comment by JaimieMurdock** [comment] 2016-10-11 16:21
I linked directly to the license at the repo. I guess part of the criticism there is related to the [FSF License Guide](https://www.gnu.org/licenses/license-list.en.html#X11License)'s criticism of referring to it as the MIT License:

    This license is sometimes called the MIT license, but that term is misleading, since MIT has used many licenses for software.

I suppose practice trumps principle though.

I've also noticed that many projects recommend the [Apache License](https://opensource.org/licenses/Apache-2.0) instead for projects of our scale. I don't think there's actual evidence that the patent clause really does anything to prevent lawsuits, and like the simplicity of MIT.

**Comment by JaimieMurdock** [comment] 2016-10-20 00:36
The only unresolved thing about the layout: I'm not sure about Apache vs. MIT license and would just like a second opinion. ([Quota on differences between licenses](https://www.quora.com/Whats-the-different-between-Apache-v2-0-and-MIT-license))

TODOs
- [ ] change "MIT-style license" to "MIT license".
- [ ] add explicit Creative Commons BY license to derviative visualizations.
- [ ] merge to master branch.

**Comment by JaimieMurdock** [comment] 2016-10-24 22:41
In person conversation confirmed MIT License decision. Moving ahead with changes.

**Comment by JaimieMurdock** [comment] 2016-10-30 20:45
Fixed in `1.0b136`

**Closed by JaimieMurdock** 2016-10-30 20:45 UTC
