### ISSUE TITLE
"option values must be strings." error

### ISSUE THREAD

**Issue by brandontlocke** [inpho/topic-explorer#352] opened 2019-04-04 23:19 UTC
When I try to train or prep, I am repeatedly getting the same error - "option values must be strings."  I've now tried it with two different folders of text files and I'm getting the same thing every time. Am I missing something?

```Traceback (most recent call last):
  File "/Users/lblackw/anaconda3/bin/topicexplorer", line 11, in <module>
    sys.exit(main())
  File "/Users/lblackw/anaconda3/lib/python3.7/site-packages/topicexplorer/__main__.py", line 243, in main
    benchmark(train.main)(args)
  File "/Users/lblackw/anaconda3/lib/python3.7/site-packages/topicexplorer/train.py", line 211, in main
    config = topicexplorer.config.read(args.config_file)
  File "/Users/lblackw/anaconda3/lib/python3.7/site-packages/topicexplorer/config.py", line 32, in read
    'tokenizer': 'default'
  File "/Users/lblackw/anaconda3/lib/python3.7/configparser.py", line 638, in __init__
    self._read_defaults(defaults)
  File "/Users/lblackw/anaconda3/lib/python3.7/configparser.py", line 1216, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "/Users/lblackw/anaconda3/lib/python3.7/configparser.py", line 753, in read_dict
    self.set(section, key, value)
  File "/Users/lblackw/anaconda3/lib/python3.7/configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)
  File "/Users/lblackw/anaconda3/lib/python3.7/configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")```

**Comment by JaimieMurdock** [comment] 2019-04-08 00:31
i will investigate this on Tuesday and provide an update here.

**Comment by JaimieMurdock** [comment] 2019-04-10 05:33
It looks like this is an issue with a change to Python 3.7 in `configparser`.

@RamIyer1998, I think you were having this issue too. Could you first reproduce with whatever version you have now? After that, could you retry it with the change to master (a2f1ec8). Then I'll create a new release tomorrow.

**Comment by RamIyer1998** [comment] 2019-04-10 15:15
@JaimieMurdock So I reproduced it on version `1.0b219-21-gc752806`, and then updated. It seems to work now! The only thing is that I had to rebuild the corpus that I built on the previous version, otherwise it said that `X.ini` was an invalid config file when I tried to prep the corpus or launch it. After I rebuilt the corpus however, it seems to be prepping fine.

**Comment by JaimieMurdock** [comment] 2019-04-11 05:45
Awesome on the initial fix working, The invalid config file issue is interesting - perhaps you could upload X.ini here? Maybe it *is* an invalid config file!

**Comment by JaimieMurdock** [comment] 2019-04-18 17:09
I was able to replicate the invalid config files and found the root of a lot of errors: I had refactored the config files to use a single parser in `topicexplorer.config` however, I didn't refactor a lot of the extensions or the import/export function, so we've been having lots of errors on recent builds. 

I'm correcting those now and will push a new release by 6pm eastern.

**Comment by JaimieMurdock** [comment] 2019-04-18 19:16
@brandontlocke This issue has been resolved with topicexplorer 1.0b223

`pip install topicexplorer==1.0b223` should get you the upgrade!

**Closed by JaimieMurdock** 2019-04-18 19:16 UTC

**Comment by brandontlocke** [comment] 2019-06-22 02:34
I had to put this project down for a bit. Everything works now—thank you so much!

**Comment by JaimieMurdock** [comment] 2019-06-22 17:43
Glad to help, @brandontlocke!
