### ISSUE TITLE
directory structure error during init

### ISSUE THREAD

**Issue by colinallen** [inpho/topic-explorer#169] opened 2016-10-14 02:53 UTC
Attempting to init new HandianCorpus with the ERROR response shown below.  Note that first line of error message correctly finds all the files, so the invalid path message is nonsensical.

'''
Building corpus from HandianCorpus 18229 files, 491 dirs, 0 levels
with coll_corpus function
ERROR: invalid path, please specify either:
  * a single plain-text or PDF file,
  * a single bibtex (.bib) file with 'file' fields,
  * a folder of plain-text or PDF files, or
  * a folder of folders of plain-text or PDF files.
'''

**Comment by JaimieMurdock** [comment] 2016-10-14 03:08
Very strange, likely related to a "try/except IOError:" block in 
topicexplorer/init.py.

Does the Handian corpus still have the multi-level heirarchical 
structure? If so, TE should be using walk_corpus rather than 
coll_corpus, so something is wrong with get_corpusbuilder_fn.

**Comment by colinallen** [comment] 2016-10-14 11:31
Yep, it’s still multi-level.


On Oct 13, 2016, at 11:08 PM, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:

Very strange, likely related to a "try/except IOError:" block in
topicexplorer/init.py.

Does the Handian corpus still have the multi-level heirarchical
structure? If so, TE should be using walk_corpus rather than
coll_corpus, so something is wrong with get_corpusbuilder_fn.

**Comment by JaimieMurdock** [comment] 2016-10-16 22:08
I've narrowed the error down to [init.py:111-119](https://github.com/inpho/topic-explorer/blob/master/topicexplorer/init.py#L111-L119)
```python
    dir_counts = defaultdict(int)
    for path in relpaths:
        dir_counts[os.path.dirname(path)] += 1

    dirs = dir_counts.keys()
    populated_levels = [dir.count(os.path.sep)
                        for dir, key in dir_counts.iteritems()]
    levels = max(populated_levels) - min(populated_levels)
    print "{} files, {} dirs, {} levels".format(len(relpaths), len(dirs), levels)
```

I suspect the issue is that the new corpus only has files in the "leaf" directories, but that these leaves are nested flatly - whereas before it was a more jagged/uneven tree. This caused the line `levels = max(populated_levels) - min(populated_levels)` to evaluate to 0, even though the data was down the tree.

I'd like to confirm this before engineering a better solution. Is this corpus only on your laptop or is it on inphodata?

**Comment by colinallen** [comment] 2016-10-16 23:15
I was actually just using the old corpus so same as on inphodata.



--
http://mypage.iu.edu/~colallen/

On Oct 16, 2016, at 18:08, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:


I've narrowed the error down to init.py:111-119<https://github.com/inpho/topic-explorer/blob/master/topicexplorer/init.py#L111-L119>

    dir_counts = defaultdict(int)
    for path in relpaths:
        dir_counts[os.path.dirname(path)] += 1

    dirs = dir_counts.keys()
    populated_levels = [dir.count(os.path.sep)
                        for dir, key in dir_counts.iteritems()]
    levels = max(populated_levels) - min(populated_levels)
    print "{} files, {} dirs, {} levels".format(len(relpaths), len(dirs), levels)

I suspect the issue is that the new corpus only has files in the "leaf" directories, but that these leaves are nested flatly - whereas before it was a more jagged/uneven tree. This caused the line levels = max(populated_levels) - min(populated_levels) to evaluate to 0, even though the data was down the tree.

I'd like to confirm this before engineering a better solution. Is this corpus only on your laptop or is it on inphodata?

-

**Comment by JaimieMurdock** [comment] 2016-10-17 02:43
Waiting on unit tests for v1.0b135, then will be closed.

**Comment by colinallen** [comment] 2016-10-17 16:35
Still getting an error, so have reopened this... process terminates after 100% meter reached with "Killed" message

Corpus file found. Rebuild?  [y/N] y
Building corpus from HandianCorpus 18229 files, 491 dirs, 0 levels
with walk_corpus function
100%|##########################################################################|
Killed

**Comment by JaimieMurdock** [comment] 2016-10-17 23:32
The issue there is just running out of memory - will have to free some up on inphodata. For the future, we can do modeling on IU's [mason supercomputer](https://kb.iu.edu/d/bbhh) until we complete some memory optimizations.

**Comment by colinallen** [comment] 2016-10-18 00:02
Actually, this was on my laptop so will have to see what I can do to free some up here- thanks!



--
http://mypage.iu.edu/~colallen/

On Oct 17, 2016, at 19:33, Jaimie Murdock <notifications@github.com<mailto:notifications@github.com>> wrote:


The issue there is just running out of memory - will have to free some up on inphodata. For the future, we can do modeling on IU's mason supercomputer<https://kb.iu.edu/d/bbhh> until we complete some memory optimizations.

-

**Comment by JaimieMurdock** [comment] 2016-10-18 18:25
Interesting that Mac OS reports "Killed" on a MemoryError, rather than 
reporting the error as on our Debian boxes.

**Comment by JaimieMurdock** [comment] 2016-10-19 04:03
Since the original bug report, which is that `walk_corpus` was not being called, has been fixed I am closing this again.

**Closed by JaimieMurdock** 2016-10-19 04:03 UTC
